### PR TITLE
feat(grpc): add v1/host service

### PR DESCRIPTION
**Pull request by akhilerm**
Signed-off-by: Akhil Mohan <akhil.mohan@datacore.com>

### CODE REVIEW

**Review by shubham14bajpai — APPROVED** [review]
LGTM

**Comment by akhilerm** [comment]
@mtzaurus @tiagolobocastro Can you take a look at this PR?

**Comment by akhilerm** [comment]
@mtzaurus @tiagolobocastro Can you take a look at this PR and merge it?

**Review by shubham14bajpai — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Comment by mtzaurus** [comment]
bors merge

**Pull request merged**
